### ISSUE TITLE
[Bug] Failed loading libhidapi.dylib on M1 mac due to homebrew path changed

### ISSUE THREAD

**Issue by LSChyi** [qmk/qmk_cli#60] opened 2021-06-24 14:29 UTC
Can not compile firmware even dependencies are fulfilled.

## Describe the Bug
After manually installed the `osx-cross/avr/avr-gcc` (which installs avr-gcc@9 at the time present) and `arm-none-eabi-gcc`, `qmk doctor` passed with just a warning about the `avr-gcc` version, I can run the build command on my M1 Macbook Pro. However, the build failed with just saying that 

```
ERROR: Can not run "qmk" command!

 Please run util/qmk_install.sh to install all the dependencies QMK requires.

make: *** [phoenix:default] Error 1
```

After digging into the code, I found that it fails at loading the dynamic library HIDAPI, which fails at the `__init__.py` of the hid site package. I checked my `LD_LIBRARY_PATH` and the `libhidapi.dylib` is right there.

This happens because the homebrew path changed on M1 machines into `/opt/homebrew`, thus the search failed. I know this may not be the issue of `qmk_cli`, but there are some improvements we can make:

1. Improve the error message without just saying `ERROR: Can not run "qmk" command!`, at least make the error clear with different log levels such as debug.
2. Find a workaround for fixing this:
    *  Could be setting some environment variables to make the search of dynamic library successful? I am not sure about that because looks like it is using another process without passing environment variables.
    * Document the workaround such as make a soft link pointing to the old search path.

## Additional Context

I have tested by manually setting the load path to 

```
hidapi = ctypes.cdll.LoadLibrary("/opt/homebrew/lib/libhidapi.dylib")
```

in `/opt/homebrew/Cellar/qmk/0.0.52/libexec/lib/python3.9/site-packages/hid/__init__.py` and I can compile the firmware without any problem.

**Comment by LSChyi** [comment] 2021-06-24 15:53
I checked the [ctyes documentation](https://docs.python.org/3/library/ctypes.html), although they only document that the search path can be altered by setting the environment variable `LD_LIBRARY_PATH `, I tested on my M1 mac with/without setting the `DYLD_LIBRARY_PATH` and the search also works:

```
bash-3.2$ echo $DYLD_LIBRARY_PATH

bash-3.2$ python
Python 3.9.5 (default, May  3 2021, 19:12:05)
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import hid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/hid/__init__.py", line 30, in <module>
    raise ImportError(error)
ImportError: Unable to load any of the following libraries:libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dll
>>>
bash-3.2$ export DYLD_LIBRARY_PATH=/opt/homebrew/lib
bash-3.2$ python
Python 3.9.5 (default, May  3 2021, 19:12:05)
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import hid
>>>
```

As a result, I think there is a problem in this project that the `DYLD_LIBRARY_PATH` is not passed with the `run_cmd`:

https://github.com/qmk/qmk_cli/blob/0475193870424e4b00af213fff7e68a01ceacf7e/qmk_cli/script_qmk.py#L33-L41

Probably we should document this dynamic library search path environment variable and fix the environment variable is not passed.

**Comment by skullydazed** [comment] 2021-06-24 15:57
There's a few things going on here to unpack...

First, you likely need more than just those two packages, the dependencies for mac are set here in our homebrew tap:

https://github.com/qmk/homebrew-qmk/blob/master/qmk.rb#L9-L20

Second, building QMK on an arm mac requires using rosetta at the current time. It's not clear when all the tools we need will be working on arm mac. I recommend removing your current brew installation and reinstalling with:

    arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

If you want to live on the bleeding and try out native ARM building anyway you probably need to `export LD_LIBRARY_PATH` and/or `export DYLD_LIBRARY_PATH` so its available to child processes. That's the most likely reason you're running into that. I'll also note it's extremely rare for either of those environment variables to need to be set in the first place and point to an irregularity in your environment.

**Comment by LSChyi** [comment] 2021-06-24 16:06
@skullydazed I have the native `avr-gcc` and `arm-avr-gcc`, and both are working correctly, check this out:

```
/opt/homebrew/Cellar/avr-gcc@9/9.3.0_3/bin   stable  file avr-gcc
avr-gcc: Mach-O 64-bit executable arm64
```

So supposedly there is nothing to do with rosetta. The root cause is as I described, it is the dynamic library search path is wrong.

Also, if you check the first comment, I already make the test of setting the `LD_LIBRARY_PATH `, and it is not working due to the subprocess call in qmk cli does not pass the parent environment variables.

**Comment by skullydazed** [comment] 2021-06-24 16:17
The QMK CLI is not sanitizing or otherwise changing the environment when subprocesses are run. If the variable is set when you run `qmk compile` it will be passed down to subsequent commands. I suppose it's possible `make` is stripping that out somewhere, and that would be a separate bug to find and track down.

That aside, can you explain why you're setting `LD_LIBRARY_PATH` in the first place? [Homebrew says it's not needed.](https://github.com/Homebrew/brew/issues/9214)

**Comment by LSChyi** [comment] 2021-06-24 16:24
@skullydazed setting the `LD_LIBRARY_PATH` is for your process to find the dynamic library, and here the problem is that qmk cli import hid package, which requires to load dynamic library, so setting the `LD_LIBRARY_PATH ` is for the python process to load the dynamic library with the right path, not for homebrew.

If you check out the code, you will know that `qmk compile` makes a subprocess call of `make`. Also, I tested by calling the `qmk compile` directly without using make:

```
qmk compile -kb phoenix -km default
Ψ Compiling keymap with make -j 1 phoenix:default


QMK Firmware 0.13.14
Making phoenix with keymap default

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/qmk/0.0.52/libexec/lib/python3.9/site-packages/qmk_cli/script_qmk.py", line 77, in main
    import qmk.cli  # noqa
  File "/Users/lschyi/code/c/qmk_firmware/lib/python/qmk/cli/__init__.py", line 192, in <module>
    __import__(subcommand)
  File "/Users/lschyi/code/c/qmk_firmware/lib/python/qmk/cli/console.py", line 9, in <module>
    import hid
  File "/opt/homebrew/Cellar/qmk/0.0.52/libexec/lib/python3.9/site-packages/hid/__init__.py", line 31, in <module>
    raise ImportError(error)
ImportError: Unable to load any of the following libraries:libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dll
build_keyboard.mk:104: fuck: No such file or directory
build_keyboard.mk:104: Error:: No such file or directory
build_keyboard.mk:104: %s:: No such file or directory
build_keyboard.mk:104: %s: No such file or directory
build_keyboard.mk:104: ('ImportError',: No such file or directory
build_keyboard.mk:104: ImportError('Unable): No such file or directory
build_keyboard.mk:104: ImportError(to): No such file or directory
build_keyboard.mk:104: ImportError(load): No such file or directory
build_keyboard.mk:104: ImportError(any): No such file or directory
build_keyboard.mk:104: ImportError(of): No such file or directory
build_keyboard.mk:104: ImportError(the): No such file or directory
build_keyboard.mk:104: ImportError(following): No such file or directory
build_keyboard.mk:104: ImportError(libraries:libhidapi-hidraw.so): No such file or directory
build_keyboard.mk:104: ImportError(libhidapi-hidraw.so.0): No such file or directory
build_keyboard.mk:104: ImportError(libhidapi-libusb.so): No such file or directory
build_keyboard.mk:104: ImportError(libhidapi-libusb.so.0): No such file or directory
build_keyboard.mk:104: ImportError(libhidapi-iohidmanager.so): No such file or directory
build_keyboard.mk:104: ImportError(libhidapi-iohidmanager.so.0): No such file or directory
build_keyboard.mk:104: ImportError(libhidapi.dylib): No such file or directory
build_keyboard.mk:104: ImportError(hidapi.dll): No such file or directory
build_keyboard.mk:104: ImportError(libhidapi-0.dll')): No such file or directory
make[1]: *** No rule to make target `ImportError(libhidapi-0.dll'))'.  Stop.
make: *** [phoenix:default] Error 1
Make finished with errors
```

I commented out this line so that I can get some more information:

https://github.com/qmk/qmk_firmware/blob/ca2259d9863e5b7b251aaa233debacb592380aaa/Makefile#L512

Please read thoroughly about the root cause.

**Comment by skullydazed** [comment] 2021-06-24 16:34
I understand the root cause perfectly fine.

1. Homebrew instructs users to install ARM native in </opt/local> instead of </usr/local>
2. As a result the dynamic libraries aren't in the usual system paths
3. Adding LD_LIBRARY_PATH can fix it for broken software, but homebrew says it shouldn't be needed
4. At any rate, the broken package in question is not provided by QMK, this particular bug is not ours to fix.

You also seem to have a misunderstanding about how the environment is passed. The QMK CLI does not pass `env=` to the underlying `subprocess.run` call, which means it's `os.environ` which is passed down, which will include `LD_LIBRARY_PATH` if it was exported from the parent shell. You can prove this by running `qmk console`, which is the command that uses the library in question.

The error you're getting comes from a `qmk` command being run by `make`. If the `LD_LIBRARY_PATH` variable has gone missing by that point it means it's something in the `make` infrastructure.

**Comment by LSChyi** [comment] 2021-06-24 17:08
Sorry for the misunderstanding that the environment variables are missing in the `make` infrastructure, I did not know that even running `qmk compile`, the flow is to invoke a `make` process then call `qmk` afterward. Looks like there is nothing to do with qmk cli. Let's see how Homebrew prefix changes in the future, and maybe to find a better way for handling the dynamic library path.

Please feel free to close this issue as this problem is not that much related to this project for the time being.

**Comment by carlocab** [comment] 2021-06-25 17:39
@LSChyi, can you try re-compiling `python@3.9` with this patch?
```diff
diff --git a/Formula/python@3.9.rb b/Formula/python@3.9.rb
index f350df39d8..15c67d5a94 100644
--- a/Formula/python@3.9.rb
+++ b/Formula/python@3.9.rb
@@ -147,7 +147,7 @@ class PythonAT39 < Formula
     cflags         = []
     cflags_nodist  = ["-I#{HOMEBREW_PREFIX}/include"]
     ldflags        = []
-    ldflags_nodist = ["-L#{HOMEBREW_PREFIX}/lib"]
+    ldflags_nodist = ["-L#{HOMEBREW_PREFIX}/lib", "-Wl,-rpath,#{HOMEBREW_PREFIX}/lib"]
     cppflags       = ["-I#{HOMEBREW_PREFIX}/include"]
 
     if MacOS.sdk_path_if_needed
```
I think this might help the `ctypes` module find `libhidapi.dylib`.

**Comment by LSChyi** [comment] 2021-06-26 03:54
@carlocab by patching the formula with adding the ldfags option, the compilation works without any problem, great thanks!

**Comment by carlocab** [comment] 2021-06-26 04:36
I've opened Homebrew/homebrew-core#80052 to apply this fix to the formula.

**Comment by carlocab** [comment] 2021-07-04 01:33
This should have been fixed in https://github.com/Homebrew/homebrew-core/commit/a4e8cbf111fc94b0e95821bd3f413a4b7fd99ad3.

**Closed** 2021-07-17 06:53 UTC
Labels: bug
